//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loai
    {
        [Required(ErrorMessage ="Mã loại không được trống")]
        public string MaLoai { get; set; }
        [Required(ErrorMessage = "Tên loại không được trống")]
        public string TenLoai { get; set; }
        public string GhiChu { get; set; }
    }
}
