//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        [DisplayName("Mã nhân viên")]
        public string MaNV { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        [DisplayName("Tên nhân viên")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [RegularExpression("^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$", ErrorMessage = "Không đúng định dạng email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        [RegularExpression(@"^(03|05|07|08|09)+([0-9]{8})$", ErrorMessage = "Không đúng định dạng điện thoại")]
        [DisplayName("Số điện thoại")]
        public string DienThoai { get; set; }
        [Required(ErrorMessage = "Quyền không được để trống")]
        [DisplayName("Quyền")]
        public string Quyen { get; set; }
        public string MatKhau { get; set; }
        public bool Nghi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
