//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.GioHangs = new HashSet<GioHang>();
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public string MaSP { get; set; }
        [Required(ErrorMessage = "Tên không được trống")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Xuất xứ không được trống")]
        public string XuatXu { get; set; }
        [Required(ErrorMessage = "Đơn vị không được trống")]
        public string DonVi { get; set; }
        [Required(ErrorMessage = "Số lượng không được trống")]
        public int SoLuong { get; set; }
        [Required(ErrorMessage = "Giá không được trống")]
        public long Gia { get; set; }
        public string MoTa { get; set; }
        public bool KhongBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
    }
}
