//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.GioHangs = new HashSet<GioHang>();
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        [DisplayName("Mã sản phẩm")]
        public string MaSP { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm không được trống")]
        [DisplayName("Tên sản phẩm")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Xuất xứ sản phẩm không được trống")]
        [DisplayName("Xuất xứ")]
        public string XuatXu { get; set; }
        [Required(ErrorMessage = "Đơn vị sản phẩm không được trống")]
        [DisplayName("Đơn vị")]
        public string DonVi { get; set; }
        [Required(ErrorMessage = "Số lượng sản phẩm không được trống")]
        [Range(1,double.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        [DisplayName("Số lượng")]
        public int SoLuong { get; set; }
        [Required(ErrorMessage = "Giá bán sản phẩm không được trống")]
        [Range(1, double.MaxValue, ErrorMessage = "Giá bán phải lớn hơn 0")] 
        [DisplayName("Giá bán")]
        public long Gia { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        public bool KhongBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
    }
}
